export default () => [
  {
    field: 'id',
    header: 'Id',
    type: 'common',
    style: 'min-width: 8rem',
    permanentVisibility: true,
    dataType: 'numeric',
  },

  {
    field: 'name',
    header: 'Название',
    type: 'common',
    style: 'min-width: 14rem',
    permanentVisibility: true,
    dataType: 'text',
  },
  {
    field: 'address',
    header: 'Адрес',
    type: 'address',
    style: 'min-width: 14rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'inn',
    header: 'ИНН',
    type: 'common',
    style: 'min-width: 10rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'ogrn',
    header: 'ОГРН',
    type: 'common',
    style: 'min-width: 10rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'reasonSearching',
    header: 'Причины поиска',
    type: 'reasons',
    style: 'min-width: 14rem',
    permanentVisibility: true,
    dataType: 'text',
  },
  {
    field: 'phones',
    header: 'Телефон',
    type: 'common',
    style: 'min-width: 16rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'emails',
    header: 'Email',
    type: 'common',
    style: 'min-width: 20rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'management_name',
    header: 'Руководитель',
    type: 'common',
    style: 'min-width: 14rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'state_registration_date',
    header: 'Дата регистрации',
    type: 'date',
    style: 'min-width: 16rem',
    permanentVisibility: false,
    dataType: 'date',
  },
  {
    field: 'state_actuality_date',
    header: 'Дата последней активности',
    type: 'date',
    style: 'min-width: 16rem',
    permanentVisibility: false,
    dataType: 'date',
  },
  {
    field: 'okpo',
    header: 'ОКПО',
    type: 'common',
    style: 'min-width: 10rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'okato',
    header: 'ОКАТО',
    type: 'common',
    style: 'min-width: 10rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'oktmo',
    header: 'ОКТМО',
    type: 'common',
    style: 'min-width: 10rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'okogu',
    header: 'ОКОГУ',
    type: 'common',
    style: 'min-width: 10rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'okfs',
    header: 'ОКФС',
    type: 'common',
    style: 'min-width: 10rem',
    permanentVisibility: false,
    dataType: 'text',
  },
  {
    field: 'okved',
    header: 'ОКВЭД',
    type: 'common',
    style: 'min-width: 10rem',
    permanentVisibility: false,
    dataType: 'text',
  },
];
